### ISSUE TITLE
invalid augroup: session.lua

### ISSUE THREAD

**Issue by ayoubelmhamdi** [nyngwang/suave.lua#2]
Using the default setting from README.md
```log
packer.nvim: Error running config for suave.lua: [string "..."]:0: invalid augroup: session.lua
```

**Comment by nyngwang** [comment]
In short: you can simply delete all `group = 'session.lua'` from those `nvim_create_autocmd(...)`.

---

Long version: It's always a good idea to create a group for your autocmds. To do so use this syntax:

```lua
vim.api.nvim_create_augroup(YOUR_STRING, { clear = true })
```

where `YOUR_STRING` can be any string you like. Here I just forgot to remove the group name that I created for myself.
`` Sorry that I forgot to add a note on this.

**Comment by nyngwang** [comment]
@ayoubelmhamdi I just updated the README.md. (Sorry for my late update, was&am busy)
