### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by clue44** [nyngwang/suave.lua#23]
I installed the plugin and the only instruction was to create a .suave folder in the project root.

Tried that, and of course nothing happened. Looked in the source code, and appearently we should run require("suave").toggle_menu() after creating the folder? Tried that, got a message that I should create the .suave folder (it already exists in the cwd).

Would love to try the plugin but I really dont know what to do after creating the .suave folder in the cwd. The README should probably have some instructions what to do next. :)

**Comment by nyngwang** [comment]
Hi @clue44: 

It will be great if you could share more background info (your operating system, some description about the project you have tried and failed, how did you start the project, etc).

**Comment by nyngwang** [comment]
Closing as I'm not sure whether you're still interested in solving this problem. Feel free to reopen it if you have time and can provide more information.
